[Test] make sure internet is working before running
It could happen that we get a network issue while running tests:

```
java.io.IOException: Server returned HTTP response code: 503 for URL: http://dumps.wikimedia.org/frwiki/latest/frwiki-latest-pages-articles.xml.bz2
```

We should try to limit those failures by detecting if the URL is responding before trying to create the river.

Closes #44.
(cherry picked from commit 1bcd21b)
(cherry picked from commit 83c7ac4)